# Generated by Django 3.2.7 on 2021-10-07 10:51

from django.db import migrations, models
import django.db.models.deletion
import xplur_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplur_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to=xplur_app.models.img_path)),
                ('large_icon', models.ImageField(blank=True, null=True, upload_to=xplur_app.models.img_path)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xplur_app.metadata'),
        ),
    ]
